version: '3.8'

services:
  rss-reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - rss-data:/app/data
    environment:
      - PORT=8080
      # Add any other environment variables your application needs here
    restart: unless-stopped

volumes:
  rss-data:
    # This volume will persist the RSS feed data between container restarts
